### ISSUE TITLE
Create function to scrape data

### ISSUE THREAD

**Issue by William-Hill** [William-Hill/wakandan_name_textgenrnn#4]
Use Beautiful Soup to scrape and parse data from the Black Panther Marvel Wiki

**Comment by saswat01** [comment]
can i ask what data basically is it names or just the content

**Comment by William-Hill** [comment]
@saswat01 I wanted to scrape the names and gender from the wiki.  I ended up doing it in scrapy instead of Beautiful Soup and it worked pretty well.

**Comment by William-Hill** [comment]
Merged in your PR @saswat01.  Thanks!

**Comment by saswat01** [comment]
no problem !
